# .github/workflows/deploy.yml
name: Build and Deploy LEIKAH to Web Server

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.3'  # Match the Go version you use locally

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 26

      # Install Hugo (extended)
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.161.1"
          extended: true

      - name: Install other dependencies
        run: |
          sudo apt update && sudo apt install rsync

      - name: Build site
        run: |
          hugo mod get -u
          npm install
          hugo --minify

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 6900 haoyingcao.xyz >> ~/.ssh/known_hosts

      - name: Deploy via rsync over SSH
        run: |
          rsync -az --delete public/ -e 'ssh -p 6900' brian@haoyingcao.xyz:/var/www/leikah/public
